# Generated by Django 5.1.1 on 2025-09-02 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('role_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role_name', models.CharField(default='', max_length=9000)),
                ('role_description', models.CharField(default='', max_length=9000)),
                ('role_is_active', models.BooleanField(default=True)),
                ('role_createddate', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'USER ROLES',
                'db_table': 'user_roles',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='ActivateAccountTokenUser',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('token_token', models.CharField(default=None, editable=False, max_length=300)),
                ('token_is_used', models.BooleanField(default=False)),
                ('token_is_active', models.BooleanField(default=True)),
                ('token_created_date', models.DateTimeField(auto_now_add=True)),
                ('token_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ACTIVATE ACCOUNT TOKEN',
                'db_table': 'users_activate_account_token',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='ForgotPasswordRequestUser',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('request_token', models.CharField(default=None, editable=False, max_length=300)),
                ('request_is_used', models.BooleanField(default=False)),
                ('request_is_active', models.BooleanField(default=True)),
                ('request_created_date', models.DateTimeField(auto_now_add=True)),
                ('request_expiration_time', models.DateTimeField()),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FORGOT PASSWORD REQUESTS',
                'db_table': 'users_forgot_password_request',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionsGroup',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('permission_group_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission_group_name', models.CharField(default='', max_length=9000)),
                ('permission_group_is_global', models.BooleanField(default=False)),
                ('permission_group_description', models.CharField(default='', max_length=600, null=True)),
                ('permission_group_createddate', models.DateField(auto_now_add=True)),
                ('permission_group_createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_group_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PERMISSIONS GROUP',
                'db_table': 'user_permissions_group',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('permission_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission_name', models.CharField(default='', max_length=9000)),
                ('permission_code', models.CharField(default='', max_length=9000)),
                ('permission_createddate', models.DateField(auto_now_add=True)),
                ('permission_createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_creator', to=settings.AUTH_USER_MODEL)),
                ('permission_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_group', to='tanrail_uaa.userpermissionsgroup')),
            ],
            options={
                'verbose_name_plural': 'USER PERMISSIONS',
                'db_table': 'user_permissions',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='UserRolesWithPermissions',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('role_with_permission_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission_read_only', models.BooleanField(default=True)),
                ('role_with_permission_createddate', models.DateField(auto_now_add=True)),
                ('role_with_permission_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_with_permission_permission', to='tanrail_uaa.userpermissions')),
                ('role_with_permission_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_with_permission_role', to='tanrail_uaa.userroles')),
            ],
            options={
                'verbose_name_plural': 'ROLES WITH PERMISSIONS',
                'db_table': 'user_role_with_permissions',
                'ordering': ['-primary_key'],
            },
        ),
        migrations.CreateModel(
            name='UsersWithRoles',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('user_with_role_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_with_role_createddate', models.DateField(auto_now_add=True)),
                ('user_with_role_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_name', to='tanrail_uaa.userroles')),
                ('user_with_role_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'USERS WITH ROLES',
                'db_table': 'user_with_roles',
                'ordering': ['-primary_key'],
            },
        ),
    ]
