# Generated by Django 5.1.1 on 2024-10-03 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('coach_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('coach_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MainActivity',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('main_activity_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('train_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('train_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDone',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('route1', models.CharField(max_length=50)),
                ('route2', models.CharField(max_length=50)),
                ('route3', models.CharField(max_length=50)),
                ('route4', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=250)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanrail_service.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('coordinator_remarks', models.CharField(blank=True, max_length=250)),
                ('supervisor_remarks', models.CharField(blank=True, max_length=250)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanrail_service.coach')),
            ],
        ),
        migrations.CreateModel(
            name='ReportForActivity',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('activity_done', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanrail_service.activitydone')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanrail_service.report')),
            ],
        ),
        migrations.CreateModel(
            name='SubActivity',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sub_activity_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('main_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanrail_service.mainactivity')),
            ],
        ),
        migrations.AddField(
            model_name='activitydone',
            name='sub_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanrail_service.subactivity'),
        ),
        migrations.CreateModel(
            name='SubSubActivity',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sub_sub_activity_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sub_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanrail_service.subactivity')),
            ],
        ),
        migrations.AddField(
            model_name='activitydone',
            name='sub_sub_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanrail_service.subsubactivity'),
        ),
    ]
