# Generated by Django 5.1.1 on 2024-10-03 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanrail_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanrail_service.train'),
        ),
    ]
