# Generated by Django 5.1.1 on 2024-10-03 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanrail_service', '0003_report_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
