# Generated by Django 5.1.1 on 2024-10-04 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanrail_service', '0004_alter_report_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydone',
            name='activity_done_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
