# Generated by Django 5.1.1 on 2024-10-04 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanrail_service', '0005_activitydone_activity_done_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
