# Generated by Django 5.1.1 on 2024-10-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanrail_service', '0006_alter_report_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mainactivity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportforactivity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subsubactivity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='train',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
